import {
  accountingSoftware,
  companySizes,
  constructionIndustries,
  contactRoles,
  decisionMakerTypes,
  documentMethods,
  issueTags,
  leadSources,
  leadStatuses,
  literacyLevels,
  mainCustomerTypes,
  paymentMethods,
  primaryDevices,
  priorities,
  taskStatuses,
  ticketStatuses,
  ticketTypes,
  trialLikelihood,
  contractStatuses,
  dealStages,
} from "./options";
import type { EntityConfig, EntitySlug, FieldConfig } from "./types";

const constructionFields: FieldConfig[] = [
  { name: "industry", label: "業種", type: "select", options: constructionIndustries },
  { name: "company_size", label: "会社規模", type: "select", options: companySizes },
  { name: "monthly_projects", label: "月間案件数", type: "number", min: 0 },
  { name: "monthly_documents", label: "月間帳票数", type: "number", min: 0 },
  { name: "main_customer_type", label: "主な顧客", type: "select", options: mainCustomerTypes },
  { name: "current_document_method", label: "現在の帳票管理方法", type: "select", options: documentMethods },
  { name: "accounting_software", label: "会計ソフト", type: "select", options: accountingSoftware },
  { name: "primary_device", label: "主な利用端末", type: "select", options: primaryDevices },
  { name: "it_literacy", label: "ITリテラシー", type: "select", options: literacyLevels },
  { name: "decision_maker_type", label: "決裁者種別", type: "select", options: decisionMakerTypes },
];

export const entityConfigs = {
  leads: {
    slug: "leads",
    table: "leads",
    singular: "リード",
    plural: "リード",
    description: "流入から初回接触、課題把握、商談化までを管理します。",
    icon: "Sparkles",
    primaryField: "name",
    statusField: "status",
    searchFields: ["name", "company_name", "contact_name", "email", "phone", "source"],
    filterField: "status",
    sortFields: ["next_action_date", "created_at", "updated_at", "status"],
    listFields: ["name", "company_name", "status", "source", "issue_tags", "next_action_date"],
    detailFields: [
      "name",
      "company_name",
      "contact_name",
      "email",
      "phone",
      "status",
      "source",
      "issue_tags",
      "next_action_date",
      "industry",
      "company_size",
      "monthly_projects",
      "monthly_documents",
      "current_document_method",
      "it_literacy",
      "decision_maker_type",
      "notes",
    ],
    fields: [
      { name: "name", label: "リード名", type: "text", required: true },
      { name: "company_name", label: "会社名", type: "text", required: true },
      { name: "contact_name", label: "担当者名", type: "text" },
      { name: "email", label: "メール", type: "email" },
      { name: "phone", label: "電話番号", type: "tel" },
      { name: "status", label: "ステータス", type: "select", required: true, options: leadStatuses },
      { name: "source", label: "流入経路", type: "select", options: leadSources },
      { name: "issue_tags", label: "課題タグ", type: "multiselect", options: issueTags, grid: "full" },
      { name: "next_action_date", label: "次回アクション日", type: "date" },
      ...constructionFields,
      { name: "notes", label: "メモ", type: "textarea", grid: "full" },
    ],
    defaultValues: { status: "新規（広告以外）", issue_tags: [] },
  },
  companies: {
    slug: "companies",
    table: "companies",
    singular: "会社",
    plural: "会社",
    description: "契約・利用状況・問い合わせ・活動履歴を会社単位で束ねます。",
    icon: "Building2",
    primaryField: "name",
    statusField: "status",
    searchFields: ["name", "industry", "prefecture", "phone"],
    filterField: "industry",
    sortFields: ["next_action_date", "created_at", "updated_at", "name"],
    listFields: ["name", "industry", "company_size", "current_document_method", "monthly_documents", "next_action_date"],
    detailFields: [
      "name",
      "status",
      "industry",
      "company_size",
      "monthly_projects",
      "monthly_documents",
      "main_customer_type",
      "current_document_method",
      "accounting_software",
      "primary_device",
      "it_literacy",
      "decision_maker_type",
      "website",
      "prefecture",
      "address",
      "phone",
      "next_action_date",
      "notes",
    ],
    fields: [
      { name: "name", label: "会社名", type: "text", required: true },
      { name: "status", label: "会社ステータス", type: "select", options: ["prospect", "customer", "churned"] },
      ...constructionFields,
      { name: "website", label: "Webサイト", type: "url" },
      { name: "prefecture", label: "都道府県", type: "text" },
      { name: "address", label: "住所", type: "text", grid: "full" },
      { name: "phone", label: "代表電話", type: "tel" },
      { name: "next_action_date", label: "次回アクション日", type: "date" },
      { name: "notes", label: "メモ", type: "textarea", grid: "full" },
    ],
    defaultValues: { status: "prospect" },
  },
  contacts: {
    slug: "contacts",
    table: "contacts",
    singular: "担当者",
    plural: "担当者",
    description: "決裁者、経理、現場責任者などの関係者を管理します。",
    icon: "Users",
    primaryField: "name",
    statusField: "role",
    searchFields: ["name", "email", "phone", "mobile", "department"],
    filterField: "role",
    sortFields: ["created_at", "updated_at", "name", "role"],
    listFields: ["name", "company_id", "role", "email", "phone"],
    detailFields: ["name", "company_id", "role", "department", "email", "phone", "mobile", "decision_power", "notes"],
    fields: [
      { name: "company_id", label: "会社", type: "select", relation: "companies", required: true },
      { name: "name", label: "氏名", type: "text", required: true },
      { name: "role", label: "役割", type: "select", required: true, options: contactRoles },
      { name: "department", label: "部署", type: "text" },
      { name: "email", label: "メール", type: "email" },
      { name: "phone", label: "電話", type: "tel" },
      { name: "mobile", label: "携帯", type: "tel" },
      { name: "decision_power", label: "決裁影響度", type: "select", options: ["高", "中", "低"] },
      { name: "notes", label: "メモ", type: "textarea", grid: "full" },
    ],
    defaultValues: { role: "その他" },
  },
  deals: {
    slug: "deals",
    table: "deals",
    singular: "商談",
    plural: "商談",
    description: "商談ステージ、受注確度、MRR/ARR、トライアルを追跡します。",
    icon: "Handshake",
    primaryField: "name",
    statusField: "stage",
    searchFields: ["name", "stage", "expected_plan", "lost_reason", "lead_id", "contact_id"],
    filterField: "stage",
    sortFields: ["expected_contract_date", "expected_mrr", "probability", "updated_at"],
    listFields: ["name", "company_id", "stage", "expected_plan", "expected_mrr", "probability", "expected_contract_date"],
    detailFields: [
      "name",
      "company_id",
      "contact_id",
      "lead_id",
      "stage",
      "expected_plan",
      "expected_mrr",
      "expected_arr",
      "probability",
      "expected_contract_date",
      "lost_reason",
      "next_action_date",
      "notes",
    ],
    fields: [
      { name: "company_id", label: "会社", type: "select", relation: "companies" },
      { name: "contact_id", label: "担当者", type: "select", relation: "contacts" },
      { name: "lead_id", label: "元リード", type: "select", relation: "leads" },
      { name: "name", label: "商談名", type: "text", required: true },
      { name: "stage", label: "商談ステージ", type: "select", required: true, options: dealStages },
      { name: "expected_plan", label: "想定プラン", type: "select", options: ["ライト", "スタンダード", "プロ", "エンタープライズ"] },
      { name: "expected_mrr", label: "月額見込みMRR", type: "number", min: 0, step: 1000 },
      { name: "probability", label: "受注確度(%)", type: "number", min: 0, max: 100 },
      { name: "expected_contract_date", label: "契約予定日", type: "date" },
      { name: "lost_reason", label: "失注理由", type: "text" },
      { name: "next_action_date", label: "次回アクション日", type: "date" },
      { name: "notes", label: "メモ", type: "textarea", grid: "full" },
    ],
    defaultValues: { stage: "問い合わせ / リード獲得", probability: 20, expected_mrr: 0 },
  },
  tasks: {
    slug: "tasks",
    table: "tasks",
    singular: "タスク",
    plural: "タスク",
    description: "今日やるべきこと、期限切れ、高優先度を一箇所で管理します。",
    icon: "ListChecks",
    primaryField: "title",
    statusField: "status",
    searchFields: ["title", "description", "priority", "status", "contact_id"],
    filterField: "status",
    sortFields: ["due_date", "priority", "created_at", "updated_at"],
    listFields: ["title", "status", "priority", "due_date", "lead_id", "company_id", "deal_id", "support_ticket_id"],
    detailFields: ["title", "description", "status", "priority", "due_date", "lead_id", "company_id", "contact_id", "deal_id", "support_ticket_id", "completed_at"],
    fields: [
      { name: "title", label: "タスク名", type: "text", required: true },
      { name: "description", label: "内容", type: "textarea", grid: "full" },
      { name: "status", label: "ステータス", type: "select", required: true, options: taskStatuses },
      { name: "priority", label: "優先度", type: "select", required: true, options: priorities },
      { name: "due_date", label: "期限", type: "date" },
      { name: "lead_id", label: "リード", type: "select", relation: "leads" },
      { name: "company_id", label: "会社", type: "select", relation: "companies" },
      { name: "contact_id", label: "担当者", type: "select", relation: "contacts" },
      { name: "deal_id", label: "商談", type: "select", relation: "deals" },
      { name: "support_ticket_id", label: "チケット", type: "select", relation: "tickets" },
    ],
    defaultValues: { status: "未完了", priority: "中" },
  },
  trials: {
    slug: "trials",
    table: "trials",
    singular: "トライアル",
    plural: "トライアル",
    description: "トライアル利用状況と有料化見込みを手入力・将来API連携前提で管理します。",
    icon: "Rocket",
    primaryField: "company_id",
    statusField: "paid_conversion_likelihood",
    searchFields: ["paid_conversion_likelihood", "notes"],
    filterField: "paid_conversion_likelihood",
    sortFields: ["end_date", "activation_level", "login_count", "updated_at"],
    listFields: ["company_id", "deal_id", "start_date", "end_date", "login_count", "activation_level", "paid_conversion_likelihood"],
    detailFields: [
      "company_id",
      "deal_id",
      "start_date",
      "end_date",
      "first_login_at",
      "login_count",
      "documents_created",
      "estimates_created",
      "invoices_created",
      "invited_users_count",
      "setup_completion_rate",
      "activation_level",
      "paid_conversion_likelihood",
      "notes",
    ],
    fields: [
      { name: "company_id", label: "会社", type: "select", relation: "companies", required: true },
      { name: "deal_id", label: "商談", type: "select", relation: "deals" },
      { name: "start_date", label: "開始日", type: "date", required: true },
      { name: "end_date", label: "終了日", type: "date", required: true },
      { name: "first_login_at", label: "初回ログイン日時", type: "datetime-local" },
      { name: "login_count", label: "ログイン回数", type: "number", min: 0 },
      { name: "documents_created", label: "帳票作成数", type: "number", min: 0 },
      { name: "estimates_created", label: "見積書作成数", type: "number", min: 0 },
      { name: "invoices_created", label: "請求書作成数", type: "number", min: 0 },
      { name: "invited_users_count", label: "招待ユーザー数", type: "number", min: 0 },
      { name: "setup_completion_rate", label: "初期設定完了率(%)", type: "number", min: 0, max: 100 },
      { name: "activation_level", label: "アクティベーションLv", type: "number", min: 0, max: 7 },
      { name: "paid_conversion_likelihood", label: "有料化見込み", type: "select", options: trialLikelihood },
      { name: "notes", label: "メモ", type: "textarea", grid: "full" },
    ],
    defaultValues: { login_count: 0, activation_level: 0, paid_conversion_likelihood: "中" },
  },
  contracts: {
    slug: "contracts",
    table: "subscriptions",
    singular: "契約",
    plural: "契約",
    description: "プラン、MRR/ARR、更新日、請求確認を管理します。",
    icon: "FileSignature",
    primaryField: "plan",
    statusField: "status",
    searchFields: ["plan", "status", "payment_method", "notes"],
    filterField: "status",
    sortFields: ["renewal_on", "mrr", "started_on", "updated_at"],
    listFields: ["company_id", "plan", "mrr", "arr", "status", "renewal_on", "payment_method"],
    detailFields: ["company_id", "plan", "mrr", "arr", "started_on", "renewal_on", "contract_period_months", "payment_method", "status", "churn_scheduled_on", "notes"],
    fields: [
      { name: "company_id", label: "会社", type: "select", relation: "companies", required: true },
      { name: "plan", label: "プラン", type: "select", required: true, options: ["ライト", "スタンダード", "プロ", "エンタープライズ"] },
      { name: "mrr", label: "MRR", type: "number", min: 0, step: 1000 },
      { name: "started_on", label: "契約開始日", type: "date", required: true },
      { name: "renewal_on", label: "契約更新日", type: "date" },
      { name: "contract_period_months", label: "契約期間(月)", type: "number", min: 1 },
      { name: "payment_method", label: "支払い方法", type: "select", options: paymentMethods },
      { name: "status", label: "契約ステータス", type: "select", required: true, options: contractStatuses },
      { name: "churn_scheduled_on", label: "解約予定日", type: "date" },
      { name: "notes", label: "メモ", type: "textarea", grid: "full" },
    ],
    defaultValues: { status: "トライアル", mrr: 0, contract_period_months: 12 },
  },
  tickets: {
    slug: "tickets",
    table: "support_tickets",
    singular: "チケット",
    plural: "チケット",
    description: "未対応、48時間超過、請求・要望・クレームを可視化します。",
    icon: "LifeBuoy",
    primaryField: "title",
    statusField: "status",
    searchFields: ["title", "description", "type", "status", "priority", "contact_id"],
    filterField: "status",
    sortFields: ["opened_at", "priority", "updated_at", "status"],
    listFields: ["title", "company_id", "type", "priority", "status", "opened_at"],
    detailFields: ["title", "description", "company_id", "contact_id", "priority", "status", "type", "opened_at", "last_response_at", "resolved_at"],
    fields: [
      { name: "company_id", label: "会社", type: "select", relation: "companies", required: true },
      { name: "contact_id", label: "担当者", type: "select", relation: "contacts" },
      { name: "title", label: "件名", type: "text", required: true },
      { name: "description", label: "内容", type: "textarea", grid: "full" },
      { name: "priority", label: "優先度", type: "select", required: true, options: priorities },
      { name: "status", label: "ステータス", type: "select", required: true, options: ticketStatuses },
      { name: "type", label: "種別", type: "select", required: true, options: ticketTypes },
      { name: "opened_at", label: "受付日時", type: "datetime-local" },
      { name: "last_response_at", label: "最終回答日時", type: "datetime-local" },
      { name: "resolved_at", label: "解決日時", type: "datetime-local" },
    ],
    defaultValues: { status: "未対応", priority: "中", type: "使い方" },
  },
} satisfies Record<EntitySlug, EntityConfig>;

export const entityOrder: EntitySlug[] = [
  "leads",
  "companies",
  "contacts",
  "deals",
  "tasks",
  "trials",
  "contracts",
  "tickets",
];

export function getEntityConfig(slug: string): EntityConfig | null {
  if (slug in entityConfigs) {
    return entityConfigs[slug as EntitySlug];
  }

  return null;
}
